## OpenCV tutorial 
* openCV is a library of python desinged to solve computer vision problems.
* it was first devloped in 1999 at intel by Gary Brad Sky and first release in 2000
* An openCV python is nothing but it is wrapper of original opencv c++

In [4]:
import cv2

### Basic operation

In [5]:
##  read the image
img1 = cv2.imread('a.jpg',1) # 1 for color
img2 = cv2.imread('a.jpg',0) # 0 for gray scale or balck & white
img3 = cv2.imread('a.jpg')

In [6]:
print(img1.astype)
print(img1.dtype)
print(img1.shape) # extra 3 for RGB  (392, 640, 3)
print(img1.size)
print()
# gray img
print(img2.astype)
print(img2.dtype)
print(img2.shape)
print(img2.size)


<built-in method astype of numpy.ndarray object at 0x000001EE77B32B20>
uint8
(392, 640, 3)
752640

<built-in method astype of numpy.ndarray object at 0x000001EE77B320D0>
uint8
(392, 640)
250880


In [12]:
# display image 
cv2.imshow("window_1",img2) 
# it take two parameter 
#    1. for name of the window
#    2. for name of image

##### waitkey() and destroyAllwindows() are neccaery function otherwise window goes crush 

# cv2.waitKey(0) # wait until a user presses a key
cv2.waitKey(2000) # wait for 2000 milliseconds
cv2.destroyAllWindows() # close window based on waitforkey parameter

In [14]:
## resize image using cv2.resize() function
resize_img = cv2.resize(img1,(500,500))
resize_img = cv2.resize(img1, (int(img1.shape[1]/2), int(img1.shape[0]/2))) # shape give list of size 
cv2.imshow("before",img1) 
cv2.imshow("afte",resize_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Face Detection 

step 1. Create a cascade classifier. It will contain the features of the face

step 2. OpenCV will read the image and the features file <br>
        Search for the row and column values of the face
        
step 3. Display the img with the reactangular face box        

In [32]:
# create a CascadeClassifier object
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
 # parameter = path of the xml file which contains the face feature

#Reading the image
img1 = cv2.imread('c.jpg',1)
img2 = cv2.imread('c.jpg') 

#convert to grayscale
img2 = cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
# both are same so no need to convt into gray scale 


cv2.imshow("a",img1)
cv2.imshow("win",img2)
cv2.waitKey(0)
cv2.destroyAllWindows()


# search co-ordinates of imag
faces = face_cascade.detectMultiScale(img2,scaleFactor = 1.05,minNeighbors=5)
# scalefactor =  decrease the shape value by 5%, until the face is found.
# smaller this value, the greater is the accuracy


# print(type(faces))

In [23]:
print(type(faces))
print(faces)

<class 'numpy.ndarray'>
[[105  16  41  41]
 [203  21  43  43]
 [255  22  38  38]
 [308  22  38  38]
 [ 52  17  49  49]
 [  4  20  43  43]]


In [33]:
# draw rectangles
for x,y,w,h in faces:
    img = cv2.rectangle(img1,(x,y),(x+w,y+h),(0,255,0),2)

# resize image 
resize = cv2.resize(img, (int(img.shape[1]*2),int(img.shape[0]*2)) )

cv2.imshow("a",resize)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [34]:
## take image using video
import time
video = cv2.VideoCapture(0)
check, frame = video.read()

time.sleep(3)

cv2.imshow("a",frame) # show only first image of the video 
cv2.waitKey(0)
video.release()
cv2.destroyAllWindows()

In [36]:
## take whole video
video = cv2.VideoCapture(0)
a=1
while True:
    a = a+1
    check, frame = video.read()
#     print(frame)
    cv2.imshow("a",frame)
    
    key = cv2.waitKey(1)
    
    if key == ord('q'):
        break
    
print(a)
video.release()
cv2.destroyAllWindows()


587


In [37]:
# face detection in the video
video = cv2.VideoCapture(0)

while True:
    check, frame = video.read()
    
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    
    faces = face_cascade.detectMultiScale(gray, scaleFactor = 1.05, minNeighbors=5)
    for x,y,w,h in faces:
        img = cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,0),2)
    
    cv2.imshow("a",img)
    key = cv2.waitKey(1)
    
    if key == ord('q'):
        break
        
video.release()
cv2.destroyAllWindows()
