#  detect cars from video or image

In [1]:
import cv2
import time

In [2]:
video = cv2.VideoCapture('a.mp4')
check, frame = video.read()

# take frame from video 
time.sleep(3)
cv2.imshow('a',frame)
cv2.waitKey(0)
# cv2.destroyAllWindows()

#convert into gray scale
gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
cv2.imshow('a',gray)
cv2.waitKey(0)
cv2.destroyAllWindows()


# detect car 
#   1. create cascade classifier object
car_cascade = cv2.CascadeClassifier('cars.xml')

In [3]:
cars = car_cascade.detectMultiScale(gray,1.05,5)

print(type(cars))
print(cars)

<class 'numpy.ndarray'>
[[326  48  49  49]
 [385   8  49  49]
 [527  84  55  55]
 [ 40 145  90  90]]


In [4]:
# draw reactangle on cars
for x,y,w,h in cars:
    img = cv2.rectangle(frame, (x,y),(x+w,y+h),(255,0,0),2 )


cv2.imshow("a",img)
cv2.waitKey(0) 
cv2.destroyAllWindows()
                        

## take full video to detect crs

In [5]:
## take full video to detect crs
video = cv2.VideoCapture('video.avi')
car_cascade = cv2.CascadeClassifier('cars.xml')

while True:
    check, frame = video.read()
    
#     convrt to gray
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    
#    detect car co-ordinates 
    cars = car_cascade.detectMultiScale(gray,1.1,1)
    
    #draw circle
    for x,y,w,h in cars:
        img = cv2.rectangle(frame,(x,y),(x+w,y+h),(0,0,255),2)
        
        
    cv2.imshow('a',img)
    key = cv2.waitKey(1)
    if key == ord('q'):
        break
        
video.release()
cv2.destroyAllWindows()