In [2]:
import pandas  as pd
import numpy as np
from sklearn import linear_model


In [4]:
df = pd.read_csv('homeprices.csv')

df

In [6]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df['price'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
model.predict([[5000]])

array([859554.79452055])

## First approches
1. using pickle


In [11]:
import pickle

In [13]:
with open('model_pickle','wb') as f:
    pickle.dump(model,f)

In [14]:
with open('model_pickle','rb') as f:
    mp = pickle.load(f)

In [15]:
mp.predict([[5000]])

array([859554.79452055])

## both pickle and joblib are same work
## diff :-
* if object carry large numpy array than joblib are more efficient


## Second approches
1. using joblib

In [16]:
from sklearn.externals import joblib

In [18]:
## save model
joblib.dump(model,'model_joblib')

['model_joblib']

In [19]:
## access model
mj = joblib.load('model_joblib')

In [21]:
mj.predict([[5000]])

array([859554.79452055])